modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL = "https://github.com/chestwise/chestwise/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Chestwise contributors"
description = '''${description}'''

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion}]"
ordering = "NONE"
side = "BOTH"

