minecraft_version=26.2
loader_version=0.19.3
fabric_version=0.158.0+26.2
forge_version=26.2-65.1.2
neoforge_version=26.2.0.67
quilt_loader_version=0.30.0

jei_version=30.27.0.189
rei_version=26.2.821
